export type ModalName =
  | 'test'
  | 'comingSoon'
  | 'deposit'
  | 'withdraw'
  | 'testTx'
  | 'depositTx'
  | 'withdrawTx'
  | 'backscratcherLockTx'
  | 'backscratcherClaimTx'
  | 'backscratcherReinvestTx'
  | 'labDepositTx'
  | 'labWithdrawTx'
  | 'labStakeTx'
  | 'IronBankSupplyTx';
