export type ModalName =
  | 'test'
  | 'comingSoon'
  | 'communityThemes'
  | 'deposit'
  | 'withdraw'
  | 'testTx'
  | 'depositTx'
  | 'addPosition'
  | 'withdrawTx'
  | 'migrateTx'
  | 'backscratcherLockTx'
  | 'backscratcherClaimTx'
  | 'backscratcherReinvestTx'
  | 'labDepositTx'
  | 'labWithdrawTx'
  | 'createLine'
  | 'labStakeTx';
