export type ModalName =
  // debt dao modals
  | 'addCollateral'
  | 'enableCollateral'
  | 'enableSpigot'
  | 'claimRevenue'
  | 'operateSpigot'
  | 'addPosition'
  | 'liquidateBorrower'
  | 'createLine'
  | 'borrow'
  | 'depositAndRepay'
  // yearn modals
  | 'test'
  | 'comingSoon'
  | 'communityThemes'
  | 'deposit'
  | 'withdraw'
  | 'testTx'
  | 'depositTx'
  | 'withdrawTx'
  | 'migrateTx'
  | 'backscratcherLockTx'
  | 'backscratcherClaimTx'
  | 'backscratcherReinvestTx'
  | 'labDepositTx'
  | 'labWithdrawTx'
  | 'labStakeTx';
