import { memoize } from 'lodash';

import { Env, Network } from '@types';

export const getEnv = memoize((): Env => {
  const {
    NODE_ENV,
    REACT_APP_VERSION,
    REACT_APP_HOST,
    REACT_APP_NETWORK,
    REACT_APP_CUSTOM_PROVIDER_HTTPS,
    REACT_APP_USE_MAINNET_FORK,
    REACT_APP_USE_SDK_MOCK,
    REACT_APP_ALLOW_DEV_MODE,
    REACT_APP_INFURA_PROJECT_ID,
    REACT_APP_ETHERSCAN_API_KEY,
    REACT_APP_ALCHEMY_API_KEY,
    REACT_APP_BLOCKNATIVE_KEY,
    REACT_APP_FORTMATIC_KEY,
    REACT_APP_PORTIS_KEY,
    REACT_APP_UNSTOPPABLE_DOMAINS_ID,
    REACT_APP_ZAPPER_API_KEY,
    REACT_APP_YEARN_SUBGRAPH_KEY,
  } = process.env;

  const isProd = NODE_ENV === 'production';

  return {
    ENV: NODE_ENV,
    VERSION: REACT_APP_VERSION ?? 'unknown',
    HOST: REACT_APP_HOST ?? isProd ? 'https://yearn.finance' : 'http://127.0.0.1:3000',
    NETWORK: (REACT_APP_NETWORK ?? 'mainnet') as Network,
    CUSTOM_PROVIDER_HTTPS: REACT_APP_CUSTOM_PROVIDER_HTTPS ?? 'http://127.0.0.1:8545/',
    USE_MAINNET_FORK: REACT_APP_USE_MAINNET_FORK === 'true',
    USE_SDK_MOCK: REACT_APP_USE_SDK_MOCK === 'true',
    ALLOW_DEV_MODE: REACT_APP_ALLOW_DEV_MODE === 'true',
    INFURA_PROJECT_ID: REACT_APP_INFURA_PROJECT_ID,
    ETHERSCAN_API_KEY: REACT_APP_ETHERSCAN_API_KEY,
    ALCHEMY_API_KEY: REACT_APP_ALCHEMY_API_KEY,
    BLOCKNATIVE_KEY: REACT_APP_BLOCKNATIVE_KEY,
    FORTMATIC_KEY: REACT_APP_FORTMATIC_KEY,
    PORTIS_KEY: REACT_APP_PORTIS_KEY,
    UNSTOPPABLE_DOMAINS_ID: REACT_APP_UNSTOPPABLE_DOMAINS_ID,
    ZAPPER_API_KEY: REACT_APP_ZAPPER_API_KEY,
    YEARN_SUBGRAPH_KEY: REACT_APP_YEARN_SUBGRAPH_KEY,
  };
});
